name: Build and push to TdA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: MVN Package
        run: ./mvnw package

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./src/main/docker/Dockerfile.jvm
          tags: tda-quarkus:latest
          outputs: type=docker,dest=/tmp/tda-quarkus.tar

      - name: Upload to TdA
        uses: Tour-de-App/upload-app@tda-25
        with:
          team_secret: ${{ secrets.TEAM_SECRET }}
          image_name: tda-quarkus
          image_path: /tmp/tda-quarkus.tar
